### ISSUE TITLE
CPU使用率高

### ISSUE THREAD

**Issue by Microflow-IO** [hengyoush/kyanos#201]
在一个普通k8s集群中观测，HTTP访问速率每分钟大概几十个，CPU是使用率平均%50

![image](https://github.com/user-attachments/assets/6a81c1b1-37bb-440a-be37-63ad9352f3e2)

开启了以下调试日志，发现HTTP请求是一个字节一个字节从内核到用户空间的，导致CPU使用率非常高

![f7b87c8822336e73447ea29b6e47318](https://github.com/user-attachments/assets/2b13307a-ad3c-4e45-bdb1-0819cb2bdc58)

**Comment by hengyoush** [comment]
> 发现HTTP请求是一个字节一个字节从内核到用户空间的
 
This behavior is due to the monitoring collection process (barad_agent) on the Tencent Cloud machine reading byte by byte, and Kyanos just monitored this behavior. 

Additionally, I did a very simple test on the Tencent Cloud machine, and the CPU usage of Kyanos is only **high during startup**, but it remains below 5% afterwards.
![image](https://github.com/user-attachments/assets/2b04a60b-8b02-4eff-bcb5-55f1ddcd80fe)

Is it always as high as shown in the picture?

**Comment by Microflow-IO** [comment]
thank you, not always
